input {
  gelf {
    port => 12201
    use_tcp => false
    use_udp => true
  }
}

filter {
  mutate {
    add_field => { "platform" => "osint-ecuador" }
  }

  # El driver gelf de Docker manda el nombre del contenedor en "host"
  mutate {
    rename => { "host" => "container_name" }
  }
}

output {
  elasticsearch {
    hosts => ["http://app3-elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
